### ISSUE TITLE
Some Issues?

### ISSUE THREAD

**Issue by tobiasgraeber** [maxbeckers/amazon-alexa-php#1]
Hi, 

first of all, thank you for you work!

I think i have found some issues /  got some questions.

1) why is the intent-name overridden by the intent-type or null instead $amazonRequest['name'] in https://github.com/maxbeckers/amazon-alexa-php/blob/master/src/Intent/Intent.php#L38 ?

-> by this, isnt it impossible to use the "supportsRequest"-Methot like described in the manual as following:

return $request->request instanceOf Request\Standard\IntentRequest &&
        'MyTestIntent' === **$request->request->intent->name**;

?

########

2) in your simple-intent-request.php example you defined the class "SimpleRequestHandler" AFTER using "new SimpleRequestHandler($responseHelper);" - this lead to an "undefined function"-Error in my case. shouldnt the Class be defined before using the "new ..."-Statement in Code?

########

3) Also u use the method "getallheaders()" here : https://github.com/maxbeckers/amazon-alexa-php/blob/master/examples/simple-intent-request.php#L14

There seems to be an Error on nginx, maybe you should implement this: http://php.net/manual/en/function.getallheaders.php#84262 

########

4) Last but not least, at the Moment i cannot use:
$validator = new RequestValidator();
$validator->validate($alexaRequest);

Using this, with an letsEncrypt Certificate i get the following error:

[proxy_fcgi:error] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught MaxBeckers\\AmazonAlexa\\Exception\\RequestInvalidSignatureException: Cert ssl verification failed. in .../src/Validation/RequestValidator.php:81\n

Stack trace:\n#0 ...src/Validation/RequestValidator.php(24): MaxBeckers\\AmazonAlexa\\Validation\\RequestValidator->validateSignature(Object(MaxBeckers\\AmazonAlexa\\Request\\Request))\n#1 ...alexa/amazon-alexa-php/examples/simple-intent-request.php(78): MaxBeckers\\AmazonAlexa\\Validation\\RequestValidator->validate(Object(MaxBeckers\\AmazonAlexa\\Request\\Request))\n#2 {main}\n  thrown in ...alexa/amazon-alexa-php/src/Validation/RequestValidator.php on line 81\n'

Any suggestions / hints / updated ?! :)
Thank you!

**Comment by maxbeckers** [comment]
Hi,
thanks for your comments.
I'll have a look for your problems. 
For your Second question, you're right, i wanted to show the most important part first. And show what needs to be done.
For your second question i'll implement a solution that you can use `getallheaders()` on apache and `$_SERVER`. It was just a simple example, because the headers for cert validation are needed.

**Comment by tobiasgraeber** [comment]
Thank you very much. Now also the cert-validation works correctly!

But there are some small new errors. Maybe you can fix them also? Im sure then it will run even better :)

**Please See:**

[Tue Jul 25 20:54:34.044546 2017] [proxy_fcgi:error] [pid 19412:tid 139702367614720] [client 72.21.217.182:37286] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string (1501008873185) at position 11 (8): Unexpected character in .../alexa/amazon-alexa-php/src/Request/Request/Standard/StandardRequest.php:33\nStack trace:\n#0 .../alexa/amazon-alexa-php/src/Request/Request/Standard/StandardRequest.php(33): 
DateTime->__construct('1501008873185')\n#1 .../alexa/amazon-alexa-php/src/Request/Request/Standard/IntentRequest.php(35): MaxBeckers\\AmazonAlexa\\Request\\Request\\Standard\\StandardRequest->setRequestData(Array)\n#2 .../alexa/amazon-alexa-php/src/Request/Request.php(100): MaxBeckers\\AmazonAlexa\\Request\\Request\\Standard\\IntentRequest::fromAmazonRequest(Array)\n#3 .../alexa/amazon-alexa-php/examples/simple-intent-request.php...\n'
[Tue Jul 25 20:55:42.947994 2017] [proxy_fcgi:error] [pid 19413:tid 139702472513280] [client xxx.xxx.xxx.xx:44596] AH01071: Got error 'PHP message: PHP Warning:  Invalid argument supplied for foreach() in .../alexa/amazon-alexa-php/src/Intent/Intent.php on line 41\n'
[Tue Jul 25 20:55:54.489937 2017] [proxy_fcgi:error] [pid 19413:tid 139702336145152] [client xxx.xxx.xxx.xx:45322] AH01071: Got error 'PHP message: PHP Warning:  Invalid argument supplied for foreach() in .../alexa/amazon-alexa-php/src/Intent/Intent.php on line 41\n'
[Tue Jul 25 20:56:05.257383 2017] [proxy_fcgi:error] [pid 19412:tid 139702626748160] [client xxx.xxx.xxx.xx:46566] AH01071: Got error 'PHP message: PHP Warning:  Invalid argument supplied for foreach() in .../alexa/amazon-alexa-php/src/Intent/Intent.php on line 41\nPHP message: PHP Fatal error:  Uncaught MaxBeckers\\AmazonAlexa\\Exception\\MissingRequestHandlerException in .../alexa/amazon-alexa-php/src/RequestHandler/RequestHandlerRegistry.php:33\nStack trace:\n#0 .../alexa/amazon-alexa-php/examples/simple-intent-request.php(114): MaxBeckers\\AmazonAlexa\\RequestHandler\\RequestHandlerRegistry->getSupportingHandler(Object(MaxBeckers\\AmazonAlexa\\Request\\Request))\n#1 {main}\n  thrown in .../alexa/amazon-alexa-php/src/RequestHandler/RequestHandlerRegistry.php on line 33\n'
[Tue Jul 25 20:56:05.535759 2017] [proxy_fcgi:error] [pid 19412:tid 139702325655296] [client xxx.xxx.xxx.xx:46570] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught MaxBeckers\\AmazonAlexa\\Exception\\MissingRequestHandlerException in .../alexa/amazon-alexa-php/src/RequestHandler/RequestHandlerRegistry.php:33\nStack trace:\n#0 .../alexa/amazon-alexa-php/examples/simple-intent-request.php(114): MaxBeckers\\AmazonAlexa\\RequestHandler\\RequestHandlerRegistry->getSupportingHandler(Object(MaxBeckers\\AmazonAlexa\\Request\\Request))\n#1 {main}\n  thrown in .../alexa/amazon-alexa-php/src/RequestHandler/RequestHandlerRegistry.php on line 33\n'

**Comment by tobiasgraeber** [comment]
Hmm... the error seems to appear if u ask alexa a minimum of 2 questions directly followed each other. Alexa responds correctly but than on the next request alaxa says that there was an error wit the skill.

logfile then shows:

 AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught MaxBeckers\\AmazonAlexa\\Exception\\MissingRequestHandlerException in .../alexa/amazon-alexa-php/src/RequestHandler/RequestHandlerRegistry.php:33\nStack trace:\n#0 .../alexa/amazon-alexa-php/examples/simple-intent-request.php(114): MaxBeckers\\AmazonAlexa\\RequestHandler\\RequestHandlerRegistry->getSupportingHandler(Object(MaxBeckers\\AmazonAlexa\\Request\\Request))\n#1 {main}\n  thrown in .../alexa/amazon-alexa-php/src/RequestHandler/RequestHandlerRegistry.php on line 33\n'
 
[Tue Jul 25 21:17:11.803512 2017] [proxy_fcgi:error] [pid 19412:tid 139702336145152] [client 54.240.197.77:53638] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught MaxBeckers\\AmazonAlexa\\Exception\\MissingRequestHandlerException in .../alexa/amazon-alexa-php/src/RequestHandler/RequestHandlerRegistry.php:33\nStack trace:\n#0 .../alexa/amazon-alexa-php/examples/simple-intent-request.php(114): MaxBeckers\\AmazonAlexa\\RequestHandler\\RequestHandlerRegistry->getSupportingHandler(Object(MaxBeckers\\AmazonAlexa\\Request\\Request))\n#1 {main}\n  thrown in .../alexa/amazon-alexa-php/src/RequestHandler/RequestHandlerRegistry.php on line 33\n'

Question:
Does alexa send somethink like an "end"-request automatically ?! Could it be that i am missing to handel this request?! how to catch it? whats the intent name?

RequestHandler/RequestHandlerRegistry.php on line 33 thows exception if Request ist not supported..

but what request happens here?! how to catch that / handle the error nicely?!

**Comment by tobiasgraeber** [comment]
Got it.

This is the Request alexa automatically sends if Session ends -> should this be respected in the Example oder can we handle this Intent per Default in you Project any better?!

**Comment by maxbeckers** [comment]
I'll have a look for the bugs tomorrow.

You'll get a `MaxBeckers\AmazonAlexa\Request\Request\Standard\SessionEndedRequest` and you can write a handler for that.

**Comment by tobiasgraeber** [comment]
Hi Thank you. I created a handler, but i dont really know how to check in supportsRequest?
Tried like this but seems not right:

public function supportsRequest(Request $request): bool  {
return $request->request instanceOf Request\Standard\SessionEndedRequest;
}

In SessionEndedRequest there is no  $request->request->type to check against, right?!

**Comment by maxbeckers** [comment]
Is should be instance of `SessionEndedRequest`, so this should work:
```php
public function supportsRequest(Request $request): bool {
return $request->request instanceOf MaxBeckers\AmazonAlexa\Request\Request\Standard\SessionEndedRequest;
}
```
You added your skill is to Handlers `supportedApplicationIds`? Yes, SessionEndedRequest has no intent.
