### ISSUE TITLE
Cannot prevent signature validation & timestamp validation

### ISSUE THREAD

**Issue by lewis-spears** [maxbeckers/amazon-alexa-php#27]
In my dev environment, I would like to override the `validateSignature()` & `validationTimestamp` methods in the `MaxBeckers\AmazonAlexa\Request\Request\AbstractRequest` for obvious reasons.

Unfortunately, I cannot override these methods as the Request classes are hardcoded in the `MaxBeckers\AmazonAlexa\Request\Request` class (line 31 - 50) which prevents me from creating my own classes to override the methods I have mentioned.

Ideally,  having a setter to override the values returned from the 2 methods I have mentioned.

**Comment by maxbeckers** [comment]
Why don't you ignore the `RequestValidator` in dev env when you want to ignore this during development?
```php
if ($env !== 'dev') {
    // Request validation
    $validator = new RequestValidator();
    $validator->validate($alexaRequest);
}
```
