### ISSUE TITLE
Interface for AbstractRequestHandler

### ISSUE THREAD

**Issue by skollro** [maxbeckers/amazon-alexa-php#56]
Using this package with one app id means `$supportedApplicationIds` has to be set for every handler.
Maybe `AbstractRequestHandler` should implement a new interface `RequestHandler` for more flexibility?
Since `AbstractRequestHandler` only contains one "real" method which checks if an app id is supported. Would PR if desired.

**Comment by maxbeckers** [comment]
I think this woudn't be really helpful. Fou your case you could write sth. like `abstract class MyAbstractRequestHandler extends AbstractRequestHandler` and set there the skillId directly to the `supportedApplicationIds` for example and extend your Handlers from your abstract class.
