### ISSUE TITLE
SSML generator should escape XML control characters

### ISSUE THREAD

**Issue by Robertof** [maxbeckers/amazon-alexa-php#57]
Hey,

first of all - thanks for your library! I encountered an issue during the use of `SSMLGenerator`. By doing something like:
```php
$generator = new SsmlGenerator();
$generator->say ("This & That");
print $generator->getSsml(), "\n";
```
An invalid SSML document is generated (and refused by Alexa), as it contains the "&" XML control character unescaped.
[This reference](https://console.bluemix.net/docs/services/text-to-speech/http.html#escape) should be useful. I think that using `htmlspecialchars` on the input provided to `say()` should be sufficient, I'll investigate.

Thanks,
Roberto

**Comment by maxbeckers** [comment]
Good point. Could be helpful in some cases. Wanna fix it and create a PR?

**Comment by Robertof** [comment]
Alright, I'll take care of it in the coming days!

**Comment by maxbeckers** [comment]
Fine, Thanks 👍
