### ISSUE TITLE
Permission Card

### ISSUE THREAD

**Issue by TheSunrise** [maxbeckers/amazon-alexa-php#59]
Hi,

Permission request for address creates an 403 HTTP Status Code but can be fixed by delivering a dynamically created permission card.

Amazon provides this new Permission Card https://developer.amazon.com/de/docs/custom-skills/device-address-api.html#permissions-card.

Could you provide this card and create an example eventually?

Thanks

**Comment by maxbeckers** [comment]
Thanks @TheSunrise
