### ISSUE TITLE
DeviceAddressInformation doesn't work

### ISSUE THREAD

**Issue by TheSunrise** [maxbeckers/amazon-alexa-php#62]
Hi,

I am trying to receive the address from a device via the DeviceAddressInformationHelper class. Calling the getAddress function only returns a Permission Error. Already tried the new Permission Card function but even when allowing the location, the exception stays. 

```
$helper = new DeviceAddressInformationHelper();
try {
    $fullAddress = $helper->getAddress($request);
} catch (\Exception $exception) {
    $fullAddress = null;
}
```

Hope you can help us through this

Thanks

**Comment by maxbeckers** [comment]
Hi @TheSunrise, i see the problem. was a `Basic` auth instead of `Bearer` Token.

**Comment by TheSunrise** [comment]
Hi @maxbeckers 

I tried the changes but still getting:

Client error: `GET https://api.eu.amazonalexa.com/v1/devices/amzn1.ask.device.xxx/settings/address` resulted in a `403 Forbidden` 
response: "type":"FORBIDDEN","message":"The authentication token is not valid."

Hope this helps

Regards
Leon

**Comment by TheSunrise** [comment]
@maxbeckers I see you updated the code and pushed a new tag but packagist didn't update to the new version. Can you trigger an update?

**Comment by maxbeckers** [comment]
Done

**Comment by TheSunrise** [comment]
@maxbeckers Awesome. Now everything works. Great job you did with this library. Thanks
