### ISSUE TITLE
Dialog.Delegate Example

### ISSUE THREAD

**Issue by tooliload** [maxbeckers/amazon-alexa-php#64]
Hello, 

can you help with an Example for Delegate with User-Dialog? Alexa return my question, but i can´t fill value of slot. 

```
$DelegateDirective = DelegateDirective::create();
$this->responseHelper->directive($DelegateDirective);	
return $this->responseHelper->respond("Wie groß bist du?");						
```

On Echo Console it will returned: 

```
            [reason] => ERROR
            [error] => MaxBeckers\AmazonAlexa\Request\Request\Error Object
                (
                    [type] => INVALID_RESPONSE
                    [message] => The following directives are not supported: DelegateDirective
                )

```

Thanks for help!

**Comment by maxbeckers** [comment]
Hi @tooliload,
have a look here: https://stackoverflow.com/a/51724409 
`Do not include outputSpeech or reprompt with the Dialog.Directive. Alexa uses the prompts defined in the dialog model to ask the user for the slot values and confirmations.`
