### ISSUE TITLE
Request validation fails if allow_url_fopen is disabled

### ISSUE THREAD

**Issue by SDPrio** [maxbeckers/amazon-alexa-php#65]
Downloading certificate in `RequestValidator->validateSignature` uses `file_get_contents` and thus depends on `allow_url_fopen` to be enabled. For security reasons this is not the case on many servers. In these cases `file_get_contents` will fail and simply return an empty string. The validation will fail as well of course.

Can be fixed by using `curl` instead or as fallback:

    if (ini_get('allow_url_fopen')) {
        $certData = @file_get_contents($request->signatureCertChainUrl);
    } else {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $request->signatureCertChainUrl);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $certData = curl_exec($ch);
        curl_close($ch);
    }

**Comment by maxbeckers** [comment]
Yes, you're right. But I would prefer to change it to guzzle, we have already in the project.

**Comment by SDPrio** [comment]
Great! Thank you very much!
