### ISSUE TITLE
Create default Handlers for base Intents

### ISSUE THREAD

**Issue by maxbeckers** [maxbeckers/amazon-alexa-php#68]
It will be helpful to create some default handlers for the base intents. For the most base intents is only a response text needed, so this can be created very abstract.
Should be created for the following base alexa intents:
* CancelIntent
* HelpIntent
* StopIntent
* NavigateHomeIntent

**Comment by fabeat** [comment]
There is also the `SessionEndedRequest` and `System.ExceptionEncountered` for which we could build some default handlers.
