### ISSUE TITLE
AudioPlayer.Play with metadata and image

### ISSUE THREAD

**Issue by etreml** [maxbeckers/amazon-alexa-php#79]
Hi,
I wrote following code with you library:

$Stream = Stream::create('https://foo.com/bar.mp3',0815,null,0);
$AlbumImage = Image::create('description','https://foo.com/bar.jpg');
$Metadata = Metadata::create('Tracktitle','Albumname',$AlbumImage);
$AudioItem = AudioItem::create($Stream,$Metadata);

And it genereates the following JSON:
```
{
 "version": "1.0",
 "sessionAttributes": [
  ]
,
 "response": {
  "directives": [
  {
    "playBehavior": "REPLACE_ALL",
    "audioItem": {
      "stream": {
         "url": "https:\/\/foo.com\/bar.mp3",
         "token": "0815",
         "offsetInMilliseconds": 0 }
,
         "metadata": {
         "title": "Tracktitle",
         "subtitle": "Albumname",
          "art": {
            "contentDescription": "description",
            "sources": "https:\/\/foo.com\/bar.jpg" }
          }
     }
,
 "type": "AudioPlayer.Play" }
]
}
}

`Acording to https://developer.amazon.com/de/docs/custom-skills/audioplayer-interface-reference.html#play it should genereate:`
{
  "type": "AudioPlayer.Play",
  "playBehavior": "valid playBehavior value such as ENQUEUE",
  "audioItem": {
    "stream": {
      "url": "https://cdn.example.com/url-of-the-stream-to-play",
      "token": "opaque token representing this stream",
      "expectedPreviousToken": "opaque token representing the previous stream",
      "offsetInMilliseconds": 0
    },
    "metadata": {
      "title": "title of the track to display",
      "subtitle": "subtitle of the track to display",
      "art": {
        "sources": [
          {
            "url": "https://cdn.example.com/url-of-the-album-art-image.png"
          }
        ]
      },
      "backgroundImage": {
        "sources": [
          {
            "url": "https://cdn.example.com/url-of-the-background-image.png"
          }
        ]
      }
    }
  }
}

Notice the "art" part:
Your library:
"art": {
"contentDescription": "description",
 "sources": "https:\/\/foo.com\/bar.jpg" }

Amazon:
"art": {
        "sources": [
          {
            "url": "https://cdn.example.com/url-of-the-album-art-image.png"
          }
        ]
      },

(sorry for wrong styling)

**Comment by maxbeckers** [comment]
Thanks for reporting. I'll fix it asap. But this week i'm in vacation. Or do you want to make a fix?

**Comment by etreml** [comment]
No need to hurry ;-) Enjoy your vacation.
I'm not familiar with this whole github push and pull and fork thingy.
I hope it's okay for you, when I wait to let the "master" do his magic.

**Comment by maxbeckers** [comment]
@etreml now I see, what's the Problem. You use it with `Image::create('description','https://foo.com/bar.jpg');`. But the second param of `Image::create` is an array of `ImageSource` Objects. So you need to do it this way: `$AlbumImage = Image::create('description',[ImageSource::create('https://foo.com/bar.jpg')]);`

**Comment by etreml** [comment]
Thank you. That solved my problem. 

Silly me ... 

Am 24.06.2019 13:55, schrieb Max Beckers:

> @etreml [1] now I see, what's the Problem. You use it with Image::create('description','https://foo.com/bar.jpg');. But the second param of Image::create is an array of ImageSource Objects. So you need to do it this way: $AlbumImage = Image::create('description',[ImageSource::create('https://foo.com/bar.jpg')]); 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

 

Links:
------
[1] https://github.com/etreml
[2]
https://github.com/maxbeckers/amazon-alexa-php/issues/79?email_source=notifications&amp;email_token=ABAOYQQ5KHJD3WNMPSZG4S3P4CY4TA5CNFSM4HZGBXF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYMVUWY#issuecomment-504978011
[3]
