### ISSUE TITLE
How to handle LaunchRequest on first invocation

### ISSUE THREAD

**Issue by valentinocossar** [maxbeckers/amazon-alexa-php#81]
Hi, I'm building my first PHP endpoint for an Alexa Skill. I see that Alexa when I run the invocation, sends a request JSON with the type LaunchRequest, how can I handle the first LaunchRequest?

Thank you!

**Comment by maxbeckers** [comment]
You need to build a LauchRequestHandler. It's nearly like an IntenRequestHandler, for this you can have a look to the examples. You need to check for `LaunchRequest::class`.
