### ISSUE TITLE
Add handling for Alexa Event requests

### ISSUE THREAD

**Issue by calguy1000** [maxbeckers/amazon-alexa-php#82]
It would be useful if there was the ability to handle alexa skill events such as AlexaSkillEvent.SkillDisabled and AlexaSkillEvent.SkillPermissionAccepted which are just different request types.

**Comment by maxbeckers** [comment]
Thanks for the issue @calguy1000.

Here is the Json api description to this request types: https://developer.amazon.com/de-DE/docs/alexa/smapi/skill-events-in-alexa-skills.html

Would you like to implement them?
